### ISSUE TITLE
VPXOR     xmm0, xmm0, xmm0

### ISSUE THREAD

**Issue by icyfox168168** [bitdefender/bddisasm#68]
Not sure if there is a problem

VPXOR     xmm0, xmm0, xmm0
start XMM0 (HI_32) = 0x0000000000000000000000000000000000007ff8000000000000000000000000
start XMM0 (LO_32) = 0x00000000000000f800000000000000f000007ff8000000e800000000000000e0
ture XMM0 (HI_32) = 0x0000000000000000000000000000000000007ff8000000000000000000000000
ture XMM0 (LO_32) = 0x0000000000000000000000000000000000007ff8000000000000000000000000
fuck XMM0 (HI_32) = 0x0000000000000000000000000000000000007ff8000000000000000000000000
fuck XMM0 (LO_32) = 0x00000000000000f800000000000000f000007ff8000000000000000000000000

**Comment by vlutas** [comment]
Fixed in https://github.com/bitdefender/bddisasm/commit/bf81c647e3a7cf1e84cb968b37c7e7f82d4ecf16. 

I would like to point out two things:
1. Please refrain from using words such as _fuck_ in comments and reports
2. bdshemu is not intended to be a complete emulator, or an emulator which respects the ISA to the letter (proof that we don't care at all of some of the cases, such as AF or other flags being set in some conditions). bdshemu is intended to be only correct enough so it goes through potential shellcodes, in order to determine if they are malicious or not. I strongly advise against using bdshemu as a general purpose emulator in this regard. Of course, this does not mean that we won't fix bugs - on the contrary - it just means that there are some cases we may already be aware of, and there may be some cases which we do not wish to fix at all (like the AF, for example).

Thanks for reporting this one as well!
